version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly

  - package-ecosystem: "nuget"
    directory: "/src/cli"
    schedule:
      interval: weekly

  - package-ecosystem: "npm"
    directory: "/src/vscode-extension"
    schedule:
      interval: weekly

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
