// Base node for all AST elements
public abstract record Node;

// Expressions
public abstract record Expression : Node;

public record LiteralExpression(string Value, string Type) : Expression;
public record VariableExpression(string Name) : Expression;
public record BinaryExpression(Expression Left, Expression Right, string Operator) : Expression;
public record UnaryExpression(Expression Operand, string Operator) : Expression;
public record TernaryExpression(Expression Condition, Expression TrueExpression, Expression FalseExpression) : Expression;
public record ParenthesizedExpression(Expression Inner) : Expression;
public record StringInterpolationExpression(List<object> Parts) : Expression; // Parts can be string or Expression
public record FunctionCall(string Name, List<Expression> Arguments) : Expression;
public record ParallelFunctionCall(string Name, List<Expression> Arguments) : Expression;
public record ConsoleIsSudoExpression() : Expression;
public record ConsoleIsInteractiveExpression() : Expression;
public record ConsoleGetShellExpression() : Expression;
public record ConsolePromptYesNoExpression(Expression PromptText) : Expression;
// Dialog expressions
public record ConsoleShowMessageExpression(Expression Title, Expression Message) : Expression;
public record ConsoleShowInfoExpression(Expression Title, Expression Message) : Expression;
public record ConsoleShowWarningExpression(Expression Title, Expression Message) : Expression;
public record ConsoleShowErrorExpression(Expression Title, Expression Message) : Expression;
public record ConsoleShowSuccessExpression(Expression Title, Expression Message) : Expression;
public record ConsoleShowChoiceExpression(Expression Title, Expression Message, Expression Options, Expression? DefaultIndex) : Expression;
public record ConsoleShowMultiChoiceExpression(Expression Title, Expression Message, Expression Options, Expression? DefaultSelected) : Expression;
public record ConsoleShowConfirmExpression(Expression Title, Expression Message, Expression? DefaultButton) : Expression;
public record ConsoleShowProgressExpression(Expression Title, Expression Message, Expression Percent, Expression? CanCancel) : Expression;
public record ConsolePromptTextExpression(Expression Prompt, Expression? DefaultValue, Expression? ValidationPattern) : Expression;
public record ConsolePromptPasswordExpression(Expression Prompt) : Expression;
public record ConsolePromptNumberExpression(Expression Prompt, Expression? MinValue, Expression? MaxValue, Expression? DefaultValue) : Expression;
public record ConsolePromptFileExpression(Expression Prompt, Expression? Filter) : Expression;
public record ConsolePromptDirectoryExpression(Expression Prompt, Expression? DefaultPath) : Expression;
public record UtilityRandomExpression(Expression? MinValue, Expression? MaxValue) : Expression;
public record UtilityUuidExpression() : Expression;
public record UtilityHashExpression(Expression Text, Expression? Algorithm) : Expression;
public record UtilityBase64EncodeExpression(Expression Text) : Expression;
public record UtilityBase64DecodeExpression(Expression Text) : Expression;
public record ArrayLiteral(List<Expression> Elements, string ElementType) : Expression;
public record ArrayAccess(Expression Array, Expression Index) : Expression;
public record ArrayLength(Expression Array) : Expression;
public record ArrayIsEmpty(Expression Array) : Expression;
public record ArrayContains(Expression Array, Expression Item) : Expression;
public record ArrayReverse(Expression Array) : Expression;
public record ArrayJoinExpression(Expression Array, Expression Separator) : Expression;
public record ArraySortExpression(Expression Array, Expression? SortOrder) : Expression;
public record ArrayMergeExpression(Expression Array1, Expression Array2) : Expression;
public record ArrayShuffleExpression(Expression Array) : Expression;
public record OsIsInstalledExpression(Expression AppName) : Expression;
public record ProcessElapsedTimeExpression() : Expression;
public record ProcessIdExpression() : Expression;
public record ProcessCpuExpression() : Expression;
public record ProcessMemoryExpression() : Expression;
public record ProcessCommandExpression() : Expression;
public record ProcessStatusExpression() : Expression;
public record OsGetLinuxVersionExpression() : Expression;
public record OsGetOSExpression() : Expression;
public record WebGetExpression(Expression Url) : Expression;
public record FsDirnameExpression(Expression Path) : Expression;
public record FsFileNameExpression(Expression Path) : Expression;
public record FsExtensionExpression(Expression Path) : Expression;
public record FsParentDirNameExpression(Expression Path) : Expression;
public record FsExistsExpression(Expression Path) : Expression;
public record FsReadFileExpression(Expression FilePath) : Expression;
public record FsWriteFileExpressionPlaceholder(Expression FilePath, Expression Content) : Expression;
public record FsCopyExpression(Expression SourcePath, Expression TargetPath) : Expression;
public record FsMoveExpression(Expression SourcePath, Expression TargetPath) : Expression;
public record FsRenameExpression(Expression OldName, Expression NewName) : Expression;
public record FsDeleteExpression(Expression Path) : Expression;
public record FsFindExpression(Expression SearchPath, Expression? NamePattern) : Expression;
public record StringNamespaceCallExpression(string FunctionName, List<Expression> Arguments) : Expression;
public record FsCreateTempFolderExpression(Expression? Prefix, Expression? BaseDir) : Expression;
public record ArrayNamespaceCallExpression(string FunctionName, List<Expression> Arguments) : Expression;
public record TimerCurrentExpression() : Expression;
public record AssignmentExpression(Expression Left, Expression Right) : Expression;
public record PostIncrementExpression(Expression Operand) : Expression;
public record PostDecrementExpression(Expression Operand) : Expression;
public record PreIncrementExpression(Expression Operand) : Expression;
public record PreDecrementExpression(Expression Operand) : Expression;
public record TimerStartExpression() : Expression;
public record TimerStopExpression() : Expression;
public record ArgsHasExpression(string Flag) : Expression;
public record ArgsGetExpression(string Flag) : Expression;
public record ArgsAllExpression() : Expression;
public record GitUndoLastCommitExpression() : Expression;
public record JsonParseExpression(Expression JsonString) : Expression;
public record JsonStringifyExpression(Expression JsonObject) : Expression;
public record JsonIsValidExpression(Expression JsonString) : Expression;
public record JsonGetExpression(Expression JsonObject, Expression Path) : Expression;
public record JsonSetExpression(Expression JsonObject, Expression Path, Expression Value) : Expression;
public record JsonHasExpression(Expression JsonObject, Expression Path) : Expression;
public record JsonDeleteExpression(Expression JsonObject, Expression Path) : Expression;
public record JsonKeysExpression(Expression JsonObject) : Expression;
public record JsonValuesExpression(Expression JsonObject) : Expression;
public record JsonMergeExpression(Expression JsonObject1, Expression JsonObject2) : Expression;
public record JsonInstallDependenciesExpression() : Expression;
public record YamlParseExpression(Expression YamlString) : Expression;
public record YamlStringifyExpression(Expression YamlObject) : Expression;
public record YamlIsValidExpression(Expression YamlString) : Expression;
public record YamlGetExpression(Expression YamlObject, Expression Path) : Expression;
public record YamlSetExpression(Expression YamlObject, Expression Path, Expression Value) : Expression;
public record YamlHasExpression(Expression YamlObject, Expression Path) : Expression;
public record YamlDeleteExpression(Expression YamlObject, Expression Path) : Expression;
public record YamlKeysExpression(Expression YamlObject) : Expression;
public record YamlValuesExpression(Expression YamlObject) : Expression;
public record YamlMergeExpression(Expression YamlObject1, Expression YamlObject2) : Expression;
public record YamlInstallDependenciesExpression() : Expression;
public record LambdaExpression(List<string> Parameters, List<Statement> Body) : Expression;
public record SchedulerCronExpression(Expression CronPattern, LambdaExpression Job) : Expression;

// Statements
public abstract record Statement : Node;

public record ExpressionStatement(Expression Expression) : Statement;
public record ProgramNode(List<Statement> Statements) : Node;
public record VariableDeclaration(string Name, string Type, Expression Value, bool IsConst) : Statement;
public record FunctionDeclaration(string Name, List<(string Name, string Type)> Parameters, List<Statement> Body, string? ReturnType) : Statement;
public record ConsoleLog(Expression Message) : Statement;
public record ConsoleClearStatement() : Statement;
public record ScriptEnableDebugStatement() : Statement;
public record ScriptDisableDebugStatement() : Statement;
public record ScriptDisableGlobbingStatement() : Statement;
public record ScriptEnableGlobbingStatement() : Statement;
public record ScriptExitOnErrorStatement() : Statement;
public record ScriptContinueOnErrorStatement() : Statement;
public record ScriptDescriptionStatement(string Description) : Statement;
public record ReturnStatement(Expression? Value) : Statement;
public record IfStatement(Expression Condition, List<Statement> ThenBody, List<Statement> ElseBody) : Statement;
public record ExitStatement(Expression ExitCode) : Statement;
public record RawStatement(string Content) : Statement;
public record ForLoop(VariableDeclaration Initializer, Expression Condition, Expression Update, List<Statement> Body) : Statement;
public record ForInLoop(string VariableName, Expression Iterable, List<Statement> Body) : Statement;
public record WhileStatement(Expression Condition, List<Statement> Body) : Statement;
public record CaseClause(List<Expression> Values, List<Statement> Body, bool HasBreak);
public record DefaultClause(List<Statement> Body, bool HasBreak);
public record SwitchStatement(Expression Expression, List<CaseClause> Cases, DefaultClause? DefaultCase) : Statement;
public record BreakStatement() : Statement;
public record ContinueStatement() : Statement;
public record FsWriteFileStatement(Expression FilePath, Expression Content) : Statement;
public record FsCopyStatement(Expression SourcePath, Expression TargetPath) : Statement;
public record FsMoveStatement(Expression SourcePath, Expression TargetPath) : Statement;
public record FsRenameStatement(Expression OldName, Expression NewName) : Statement;
public record FsDeleteStatement(Expression Path) : Statement;
public record TimerStartStatement() : Statement;
public record TryCatchStatement(List<Statement> TryBody, List<Statement> CatchBody, string? ErrorMessage) : Statement;
public record ArgsDefineStatement(string LongFlag, string ShortFlag, string Description, string Type, bool IsRequired, Expression? DefaultValue) : Statement;
public record ArgsShowHelpStatement() : Statement;
public record ImportStatement(string FilePath) : Statement;
public record TemplateUpdateExpression(Expression SourceFilePath, Expression TargetFilePath) : Expression;
public record TemplateUpdateStatement(Expression SourceFilePath, Expression TargetFilePath) : Statement;
public record DeferStatement(Statement Statement) : Statement;
