title: Utah Documentation
description: Write shell scripts in TypeScript-like syntax
baseurl: ""
url: "https://utahshx.com"

# Theme configuration
remote_theme: just-the-docs/just-the-docs

# Color scheme
color_scheme: dark

# Search configuration
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true

# Navigation structure
nav_sort: case_insensitive

# Aux links
aux_links:
  "GitHub":
    - "https://github.com/polatengin/utah"

# Footer content
footer_content: "Copyright &copy; 2025 Utah Language. Distributed under MIT License."

# Plugin configuration
plugins:
  - jekyll-seo-tag

# Markdown configuration
markdown: kramdown
highlighter: rouge
mermaid:
  version: "11.9.0"
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false

# Collections
collections:
  getting-started:
    permalink: /:collection/:name/
    output: true
  language-features:
    permalink: /:collection/:name/
    output: true
  functions:
    permalink: /:collection/:name/
    output: true
  guides:
    permalink: /:collection/:name/
    output: true

# Exclude files
exclude:
  - node_modules/
  - "*.gemspec"
  - "*.gem"
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - script/
  - LICENSE.txt
  - lib/
  - bin/
  - README.md
  - Rakefile
